services:
    psql:
        image: postgres:latest
        container_name: inventory-ms
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: inventory-ms
            POSTGRES_PASSWORD: secret
        networks:
            - "network"

networks:
    network:
